import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="bg-my_bg_image bg-cover bg-fixed">

       
        <aside className="border-solid border-2 border-sky-500 min-h-screen w-40">
          s
        </aside>
        {children}
        </div>
      </body>
    </html>
  );
}
